### ISSUE TITLE
Custom Sub Name

### ISSUE THREAD

**Issue by WoodProgrammer** [mjstealey/jenkins-nginx-docker#2]
When change name at nginx configuration file default.conf nginx give 404 response code. 
Example at below  ; 

```
server {

    listen 80;
    server_name localhost;

    location ^~ /CUSTOM_LOCATION/ {
...
...
... 
}
```

How I can solve this problem.

**Comment by mjstealey** [comment]
> How I can solve this problem.

If you would like the Jenkins site to resolve at URL: [www.example.com/CUSTOM_LOCATION/]() then you'd want to update two files.

1. `JENKINS_OPTS="--prefix=/jenkins"` in the [docker-compose.yml](https://github.com/mjstealey/jenkins-nginx-docker/blob/master/docker-compose.yml#L36) file (change `jenkins` to `CUSTOM_LOCATION`)
2. `location ^~ /jenkins/` in the [default.conf](https://github.com/mjstealey/jenkins-nginx-docker/blob/master/nginx/default.conf#L6) file (change `jenkins` to `CUSTOM_LOCATION`)
    - also [here](https://github.com/mjstealey/jenkins-nginx-docker/blob/master/nginx/default.conf#L14)
    - and [here](https://github.com/mjstealey/jenkins-nginx-docker/blob/master/nginx/default.conf#L17)

Optionally you could probably alias the `CUSTOM_LOCATION` location setting of the default.conf file to point at the `/jenkins` prefix as defined in the default docker-compose.yml file.

**Comment by WoodProgrammer** [comment]
Thank you so much it worked !! 
I've read also Jenkins Offical Docs about jenkins behind nginx proxy . 
Thank you very much for your helping 👍 @mjstealey

**Comment by mjstealey** [comment]
> Thank you so much it worked

@WoodProgrammer - Glad to hear things are working for you now!
Let me know if you encounter any other issues.
